version: '2'

services:

  app1:
    build:
      context: . # we pass in the entire basic-go application to can re-use shared go.mod, etc
      dockerfile: app1/Dockerfile
    ports:
      - "9000:8080"
    entrypoint:
      - "/usr/local/bin/aws-lambda-rie"
    develop:
      watch:
        - action: rebuild
          path: app1
        - action: rebuild
          path: docker-compose.yaml

  app2:
    build:
      context: . # we pass in the entire basic-go application to can re-use shared go.mod, etc
      dockerfile: app2/Dockerfile
    ports:
      - "9001:8080"
    entrypoint:
      - "/usr/local/bin/aws-lambda-rie"
    develop:
      watch:
        - action: rebuild
          path: app2
        - action: rebuild
          path: docker-compose.yaml
